services:
  caddy:
    image: caddy:latest
    restart: on-failure:5
    ports:
      - "80:80"
      - "443:443"
    mem_limit: "256m"
    cpus: 0.25
    pids_limit: 50
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - caddy_gateway
      - default
    volumes:
      - caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile

  n8n:
    build: .
    container_name: n8n
    restart: always
    #user: root
    ports:
      - "5678:5678"
    mem_limit: "768m"
    cpus: 0.25
    pids_limit: 50
    logging:
      options:
        max-size: "20m"
        max-file: "3"
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_PAYLOAD_SIZE_MAX=2048
      - NODE_OPTIONS=--max-old-space-size=2048
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - DB_SQLITE_POOL_SIZE=10
      - N8N_PROXY_HOPS=1
      - N8N_RUNNERS_ENABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - NODE_FUNCTION_ALLOW_EXTERNAL=@tryfabric/martian
      - N8N_ENCRYPTION_KEY=sacf1RPBi1gEh4kGhWwFgefed+cDItY5
    volumes:
      - n8n_data:/home/node/.n8n
      - telegram_data:/home/node/.n8n-files/telegram:ro
      - ${DATA_FOLDER}/local_files:/files
    networks:
      - telegram_shared
      - caddy_gateway

volumes:
  n8n_data:
    external: true
  caddy_data:
    external: true
  telegram_data:
    external: true
    name: telegram_telegram-bot-api-data

networks:
  caddy_gateway:
    external: true
  telegram_shared:
    external: true

